name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./build.sh
    - name: Archive Quark
      uses: actions/upload-artifact@v2
      with:
        name: vm_community_taters_quark.zip
        path: vm_community_taters_quark.zip
    - name: Archive Botania
      uses: actions/upload-artifact@v2
      with:
        name: vm_community_taters_botania.zip
        path: vm_community_taters_botania.zip
